### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by 4maheshgopi** [Vaikesh/Face_Detection_Xamarin.Android#1]
How can i run this??

**Comment by Vaikesh** [comment]
@4maheshgopi,

Try running it on a device of **API Level 14 or higher.**

If you are making use of Emulator, then establish the connection with webcam for acting as the camera for virtual emulator device.

**Comment by 4maheshgopi** [comment]
I am doing it with eclipse. but it showing errors

On Mon, Feb 22, 2016 at 5:32 PM, Vaikesh K P notifications@github.com
wrote:

> @4maheshgopi https://github.com/4maheshgopi,
> 
> Try running it on a device of _API Level 14 or higher._
> 
> If you are making use of Emulator, then establish the connection with
> webcam for acting as the camera for virtual emulator device.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vaikesh/Face_Detection_Xamarin.Android/issues/1#issuecomment-187145591
> .

## 

Regards,
Mahesh G

**Comment by Vaikesh** [comment]
@4maheshgopi,

I think you want to do in **Java**.

This sample is purely written in **C#** making use of **Xamarin**.

**Comment by Vaikesh** [comment]
Refer these java codes : 
- http://www.edumobile.org/android/face-detection-example-tutorials-in-android/
- http://androidbite.blogspot.in/2012/11/android-face-detection-example.html
- http://bytefish.de/blog/face_detection_with_android/
- http://karanbalkar.com/2014/08/implement-face-detection-in-android/

![](http://bytefish.de/static/images/blog/face_detection_with_android/face_detection_with_android_app.jpg)

**Comment by 4maheshgopi** [comment]
ok then i will go for visual studei.

See, what i need is loging using face recognition. I am behind this for
last 3 months. No one were there to help me. :(

On Mon, Feb 22, 2016 at 6:06 PM, Vaikesh K P <notifications@github.com>
wrote:

> @4maheshgopi <https://github.com/4maheshgopi>,
>
> I think you want to do in *Java*.
>
> This sample is purely written in *C#* making use of *Xamarin*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vaikesh/Face_Detection_Xamarin.Android/issues/1#issuecomment-187154168>
> .
>



-- 
Regards,
Mahesh G

**Comment by Vaikesh** [comment]
@4maheshgopi,

I suggest you to look the links i had provided to you.

Using those links you can works in Eclipse.

**Comment by 4maheshgopi** [comment]
ok thank you. Is it ok to disturb you, If i need any help?

On Mon, Feb 22, 2016 at 6:14 PM, Vaikesh K P notifications@github.com
wrote:

> @4maheshgopi https://github.com/4maheshgopi,
> 
> I suggest you to look the links i had provided to you.
> 
> Using those links you can works in Eclipse.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vaikesh/Face_Detection_Xamarin.Android/issues/1#issuecomment-187156215
> .

## 

Regards,
Mahesh G

**Comment by Vaikesh** [comment]
You can contact me using Google plus, ( vaikesh4leo@gmail.com )

I'm going to close this chat
